version: '3'
services:
  registry:
    build: 
      context: ./
    image: seanly/appset:registry-2.8.1
    container_name: registry
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./registry/auth:/auth
    environment:
      - REGISTRY_HTTP_HOST=http://127.0.0.1:5000
      - REGISTRY_STORAGE=s3
      - REGISTRY_STORAGE_S3_ACCESSKEY=minioroot
      - REGISTRY_STORAGE_S3_SECRETKEY=minioroot
      - REGISTRY_STORAGE_S3_BUCKET=registry
      - REGISTRY_STORAGE_S3_REGION=us-east-1
      - REGISTRY_STORAGE_S3_REGIONENDPOINT="http://minio:9000"
      - REGISTRY_HEALTH_STORAGEDRIVER_ENABLED=false
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_LOG_LEVEL=debug
      - REGISTRY_STORAGE_REDIRECT_DISABLE=true # https://github.com/minio/minio/issues/2743#issuecomment-421490519
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm

  minio:
    image: minio/minio:RELEASE.2021-12-20T22-07-16Z
    container_name: minio
    restart: always
    command: server /data --console-address :9001
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioroot
      MINIO_ROOT_PASSWORD: minioroot
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  default:
    name: opsbox-network

volumes:
    minio-data: