Title: flare
Footer: 由 <a href="https://github.com/soulteary/docker-flare">Flare</a> ❤️ 强力驱动
OpenAppNewTab: true
OpenBookmarkNewTab: true
ShowTitle: true
Greetings: 你好
ShowSearchComponent: true
DisabledSearchAutoFocus: false
ShowDateTime: true
ShowApps: true
ShowBookmarks: true
HideSettingButton: false
HideHelpButton: false
Theme: blackboard
ShowWeather: true
Location: 北京市
EnableEncryptedLink: false
IconMode: DEFAULT
KeepLetterCase: false
