version: "3"
services:
  headlamp:
    image: ghcr.io/headlamp-k8s/headlamp:latest
    restart: always
    command: -plugins-dir=/headlamp/plugins
    ports:
      - 4466:4466

networks:
  default:
    name: opsbox-network
    external: true
