version: '3'

services:
  postgres:
    container_name: keycloak-db
    image: "postgres:15.5-alpine"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "5432"]
      interval: 1s
      timeout: 10s
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak_rw
      POSTGRES_PASSWORD: keycloak_rw@root
      PGPASSWORD: keycloak_rw@root
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data

  keycloak:
    build:
      context: .
      args:
        KEYCLOAK_VERSION: 22.0.5
    image: seanly/appset:keycloak-v22.0.5-1
    container_name: keycloak
    #command: ["start-dev"] # ip:port 
    command: >-
      start --proxy=edge 
      --hostname=9081-seanly-appset-i53a6phr9we.ws-us106.gitpod.io 
      --hostname-admin=9082-seanly-appset-i53a6phr9we.ws-us106.gitpod.io
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak_rw
      - KC_DB_PASSWORD=keycloak_rw@root
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_METRICS_ENABLED=true
      - KC_FEATURES=account2,admin2,account-api,token-exchange,docker,declarative-user-profile
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
    labels:
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.opsbox.dev`,`admin-keycloak.opsbox.dev`)"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.routers.keycloak.tls.certResolver=le"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    ports:
      - 9081:8080
      - 9082:8080

networks:
  default:
    name: opsbox-network
    external: true

volumes:
    keycloak-postgres:

# https://blog.please-open.it/ldap-keycloak/