version: '3'

services:
  postgres:
    image: "postgres:15.5-alpine"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "5432"]
      interval: 1s
      timeout: 10s
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak_rw
      POSTGRES_PASSWORD: keycloak_rw@root
      PGPASSWORD: keycloak_rw@root
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data

  keycloak:
    build:
      context: .
      args:
        KEYCLOAK_VERSION: 22.0.5
    image: seanly/appset:keycloak-v22.0.5-1
    container_name: keycloak
    command: ["start-dev"]
    restart: unless-stopped
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
    environment:
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak_rw
      - KC_DB_PASSWORD=keycloak_rw@root
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_METRICS_ENABLED=true
      - KC_FEATURES=account2,admin2,account-api,token-exchange,docker,declarative-user-profile
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
    ports:
      - 9080:8080

networks:
  default:
    name: opsbox-network
    external: true

volumes:
    keycloak-postgres:

# https://blog.please-open.it/ldap-keycloak/