version: '3'

services:
  database:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=codimd2022
      - POSTGRES_DB=codimd
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  codimd:
    build: 
      context: ./
    image: seanly/appset:codimd
    container_name: codimd
    environment:
      - CMD_DB_URL=postgres://codimd:codimd2022@database/codimd
      - CMD_USECDN=false
      - CMD_ALLOW_GRAVATAR=false
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_ANONYMOUS_EDITS=false
      - CMD_ALLOW_FREEURL=false
      - CMD_ALLOW_PDF_EXPORT=false
      - CMD_LINKIFY_HEADER_STYLE=gfm
      - CMD_IMAGE_UPLOAD_TYPE=filesystem
      - CMD_EMAIL=true
      - CMD_ALLOW_EMAIL_REGISTER=false
    depends_on:
      - database
    volumes:
      - codimd-data:/home/hackmd/app/public/uploads
    restart: always
    labels:
      - "traefik.http.routers.codimd.rule=Host(`codimd.example.dev`)"
      - "traefik.http.routers.codimd.tls=true"
      - "traefik.http.routers.codimd.tls.certResolver=le"
      - "traefik.http.services.codimd.loadbalancer.server.port=3000"
      - "traefik.http.routers.codimd.middlewares=codimd-login-redirect"
      - "traefik.http.middlewares.codimd-login-redirect.redirectregex.regex=^https://codimd.opsbox.dev/login*"
      - "traefik.http.middlewares.codimd-login-redirect.redirectregex.replacement=https://codimd.opsbox.dev/auth/oauth2"
      
networks:
  default:
    name: opsbox-network
    external: true
volumes:
    postgres-data:
    codimd-data: