version: '3'

services:
  nexus3:
    build:
      context: .
    container_name: nexus3
    image: seanly/appset:nexus3
    ports:
    - 8081:8081
    restart: unless-stopped
    environment:
      INSTALL4J_ADD_VM_PARAMS: -Xms1024m -Xmx2048m -XX:MaxDirectMemorySize=1024m
    volumes:
      - nexus3-data:/nexus-data

networks:
  default:
    name: opsbox-network
    external: true

volumes:
    nexus3-data: