version: '3'

services:
  ldapcherry:
    build:
      context: .
    image: seanly/appset:ldapcherry
    restart: unless-stopped
    ports:
      - 8080:8080
    tty: true
    volumes:
    - ./conf:/etc/ldapcherry

networks:
  default:
    name: opsbox-network
    external: true

volumes:
    openldap-data:
  
# client:
#   1. https://directory.apache.org/studio/